SELECT ID AS EMP_ID,
        INITCAP(TRIM(NAME)) AS FULL_NAME,
        INITCAP(TRIM(CITY)) AS CITY,
        CURRENT_DATE AS LAST_MODIFIED_DATE,
        CURRENT_USER AS LAST_MODIFIED_USER
FROM EMP_T